/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData popularity = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bag = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData shopping_cart = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData basket = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData basket_1 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData edit_location = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData add_location = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData local_phone = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData local_pizza = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData my_location = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData location_on = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData location_off = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData local_grocery_store = const IconData(0xe80f, fontFamily: _kFontFam);
}
